### ISSUE TITLE
Create a pencil mockup of a viz based on data

### ISSUE THREAD

**Issue by irenatfh** [himchanjung/bna-2020-bus-ted#12]

**Comment by himchanjung** [comment]
How did the SFMTA shutdown and Coronavirus impact bikeshare usage? Especially in those areas hit hardest by the shutdown (those without access to reliable transportation)

**FAQ: BIKING DURING SHELTER IN PLACE**
https://sfbike.org/news/faq-biking-during-shelter-in-place/

**General Bikeshare Feed Specification (GBFS)**
https://github.com/NABSA/gbfs/blob/master/gbfs.md

**BayWheels Ridership Data**
https://s3.amazonaws.com/baywheels-data/index.html
