### ISSUE TITLE
Based on pencil mockups, prototype digital FIGMA mockup of our interactive.

### ISSUE THREAD

**Issue by himchanjung** [himchanjung/bna-2020-bus-ted#7]
https://github.com/himchanjung/bna-2020-bus-ted/projects/1#card-36812976

[Pencil mockup of timeline](https://drive.google.com/open?id=1CGbvCsq0nd5PwnVIltWSSETnlh62Nkmi)

**Comment by irenatfh** [comment]
Moving the Figma mockup link to this issue: https://www.figma.com/file/wsasyG3cTQNw5iCS47qkZd/bus-ted?node-id=0%3A1
